services:
  nginx:
    image: nginx:1.27.4-alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - user_service
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done'"
    depends_on:
      - nginx

  user_service:
    build: ../services/user_auth
    depends_on:
      - db    
    env_file:
      - .env
      - ../services/user_auth/.env
    volumes:
      - ./logs/user-auth:/logs
      - ./keys/public.pem:/app/public.pem
      - ./keys/private.pem:/app/private.pem
  resume_service:
    build: ../services/resume
    env_file:
      - .env
      - ../services/resume/.env
    volumes:
      - ./logs/resume:/logs
      - ./keys/public.pem:/app/public.pem
  db:
    image: postgres:17.2-alpine
    restart: on-failure
    ports:
      - "${PG_EXPOSED_PORT}:5432"
    env_file:
      - .env
      - ../services/user_auth/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
      image: redis:7.2-alpine
      restart: on-failure
      volumes:
        - redisdata:/data
      ports:
        - "${REDIS_EXPOSED_PORT}:6379"
      env_file:
        - .env  
  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./logs:/var/log/app
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.3.0
    ports:
      - "9090:9090"
    volumes:
      - prometheusdata:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
volumes:
  pgdata:
  certbot-www:
  letsencrypt:
  redisdata:
  logs:
  grafana-storage:
  prometheusdata: