services:
  nginx:
    image: nginx:1.27.4-alpine-slim
    depends_on:
      - user_service
      - resume_service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done'"
    depends_on:
      - nginx

  user_service:
    build: ../services/user_auth
    depends_on:
      kafka:
        condition: service_healthy      
    env_file:
      - .env
      - ../services/user_auth/.env
    volumes:
      - ./logs/user-auth:/logs
      - ./keys/public.pem:/app/public.pem
      - ./keys/private.pem:/app/private.pem
  postgres:
    build: ./pg_cron
    restart: on-failure
    ports:
      - "${PG_EXPOSED_PORT}:5432"
    env_file:
      - .env
      - ../services/user_auth/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
      image: redis:7.2-alpine
      restart: on-failure
      volumes:
        - redisdata:/data
      ports:
        - "${REDIS_EXPOSED_PORT}:6379"
      env_file:
        - .env  
  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./logs:/var/log/app
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.3.0
    ports:
      - "9090:9090"
    volumes:
      - prometheusdata:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  resume_service:
    build: ../services/resume
    depends_on:
      kafka:
        condition: service_healthy  
    env_file:
      - .env
      - ../services/resume/.env
    volumes:
      - ./logs/resume:/logs
      - ./keys/public.pem:/app/public.pem
  mongo:
    image: mongo:8.0.8
    env_file:
      - ../services/resume/.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka", "9092"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s
      disable: false
    volumes:
      - kafka-data:/var/lib/kafka/data
volumes:
  pgdata:
  certbot-www:
  letsencrypt:
  redisdata:
  logs:
  grafana-storage:
  prometheusdata:
  mongodb_data:
  loki_data:
  kafka-data:
  zookeeper-data:
  zookeeper-log: