"""add index for expired_at

Revision ID: 0697914db97c
Revises: ab813b45e8d9
Create Date: 2025-04-30 23:31:46.105230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0697914db97c'
down_revision: Union[str, None] = 'ab813b45e8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_expired_at'), 'refresh_tokens', ['expired_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_expired_at'), table_name='refresh_tokens')
    # ### end Alembic commands ###
