"""Init

Revision ID: 46fdd834ed2c
Revises: 
Create Date: 2025-03-01 20:43:39.983980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fdd834ed2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('expired_at', sa.Date(), server_default=sa.text('CURRENT_DATE + make_interval(secs=>2592000.0)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('ix_refresh_token_hash', 'refresh_tokens', ['refresh_token'], unique=False, postgresql_using='hash')
    op.create_index('ix_refresh_user_id', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_hash', table_name='refresh_tokens', postgresql_using='hash')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
