"""change refresh_token to refresh_jti

Revision ID: 642672ccb376
Revises: be014f87adb9
Create Date: 2025-04-02 20:51:50.121999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642672ccb376'
down_revision: Union[str, None] = 'be014f87adb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_jti', sa.String(), nullable=False), schema='user_auth')
    op.drop_constraint('refresh_tokens_refresh_token_key', 'refresh_tokens', schema='user_auth', type_='unique')
    op.create_unique_constraint(None, 'refresh_tokens', ['refresh_jti'], schema='user_auth')
    op.drop_column('refresh_tokens', 'refresh_token', schema='user_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False), schema='user_auth')
    op.drop_constraint(None, 'refresh_tokens', schema='user_auth', type_='unique')
    op.create_unique_constraint('refresh_tokens_refresh_token_key', 'refresh_tokens', ['refresh_token'], schema='user_auth')
    op.drop_column('refresh_tokens', 'refresh_jti', schema='user_auth')
    # ### end Alembic commands ###
