"""remove permissions

Revision ID: bca89e4ab67d
Revises: 642672ccb376
Create Date: 2025-04-05 23:35:05.775454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca89e4ab67d'
down_revision: Union[str, None] = '642672ccb376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank_permissions', schema='user_auth')
    op.drop_index('ix_user_auth_permissions_id', table_name='permissions', schema='user_auth')
    op.drop_table('permissions', schema='user_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_auth.permissions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('name', name='permissions_name_key'),
    schema='user_auth',
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_auth_permissions_id', 'permissions', ['id'], unique=False, schema='user_auth')
    op.create_table('rank_permissions',
    sa.Column('rank_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['user_auth.permissions.id'], name='rank_permissions_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rank_id'], ['user_auth.ranks.id'], name='rank_permissions_rank_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rank_id', 'permission_id', name='rank_permissions_pkey'),
    schema='user_auth'
    )
    # ### end Alembic commands ###
