"""change timestamp

Revision ID: be014f87adb9
Revises: 84164c6f5a95
Create Date: 2025-04-02 20:17:31.635063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be014f87adb9"
down_revision: Union[str, None] = "84164c6f5a95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_tokens",
        "expired_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("TIMEZONE('UTC', NOW()) + INTERVAL '30 days'"),
        schema="user_auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_tokens",
        "expired_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "(CURRENT_DATE + make_interval(secs => (2592000.0)::double precision))"
        ),
        schema="user_auth",
    )
    # ### end Alembic commands ###
